### ISSUE TITLE
example can not run

### ISSUE THREAD

**Issue by oikomi** [datafusion-contrib/datafusion-federation#13]
when run the example , cause error like:
`error: failed to run custom build command for `substrait v0.20.3``

**Comment by backkem** [comment]
Are there any more details to the error? Since Substrait uses Protocol Buffers, you may need to install the [Protobuf Compiler](https://github.com/protocolbuffers/protobuf?tab=readme-ov-file#protobuf-compiler-installation).

**Comment by oikomi** [comment]
> Are there any more details to the error? Since Substrait uses Protocol Buffers, you may need to install the [Protobuf Compiler](https://github.com/protocolbuffers/protobuf?tab=readme-ov-file#protobuf-compiler-installation).

Thank you , success run
