### ISSUE TITLE
Support Batched Execution via an Async Stream in CXExecutor

### ISSUE THREAD

**Issue by devinjdangelo** [datafusion-contrib/datafusion-federation#2]
The connectorX project adds a lot of value, but out of the box does not seem to support async streams. The pseudo iterator returned by https://github.com/sfu-db/connector-x/blob/05283cfe6a699d50dfefe345fb9d06c9667dc490/connectorx/src/get_arrow.rs#L238 does not get us all of the way there either since it is not thread safe.

We will need some alternative way to incrementally process a query via connectorX in batches within a `RecordBatchStream`.

**Comment by backkem** [comment]
I used ConnectorX mostly because it was convenient. However, it seems somewhat ill maintained (as evident by using a fork). I was also planning to look for an alternative.

**Comment by devinjdangelo** [comment]
Yeah, it would be great if ConnectorX could work since it supports returning RecordBatches natively. Alternatives like sqlx support async streams, but I think there would be a decent amount of work mapping database types to arrow. 

```rust
let mut stream = sqlx::query("SELECT * FROM users")
    .map(|row: PgRow| {
        // PgRow to arrow RecordBatch here
    })
    .fetch(&mut conn);
```

We could use FlightSQL client, which postgres supports https://www.postgresql.org/about/news/apache-arrow-flight-sql-adapter-for-postgresql-010-2716/. This would likely have great performance since the adapter would send arrow data over the wire and not require deserialization on the client side. Not many sources support this right now though.

There is also https://github.com/pacman82/arrow-odbc and maybe https://arrow.apache.org/docs/java/jdbc.html as options. These would have inherently worse performance since row-oriented data would be sent over the wire and then converted to arrow on the client side. Likely much better compatibility in the short term though.

**Comment by backkem** [comment]
As @devinjdangelo mentioned on Discord, maybe @aljazerzen's [connector_arrow](https://github.com/aljazerzen/connector_arrow) would be a good alternative to ConnectorX.

**Comment by backkem** [comment]
Closing in favor of the implementation in [datafusion-table-providers](https://github.com/datafusion-contrib/datafusion-table-providers/).
