### ISSUE TITLE
How do Federated Node contain "Predicate pushdown" ?

### ISSUE THREAD

**Issue by oikomi** [datafusion-contrib/datafusion-federation#23]
hello all

I have test a sql like 
`SELECT
             t.TrackId,
             t.Name AS TrackName,
             a.Title AS AlbumTitle,
             ar.Name AS ArtistName
         FROM Track t
         JOIN Album a ON t.AlbumId = a.AlbumId
         JOIN Artist ar ON a.ArtistId = ar.ArtistId
         WHERE t.TrackId > 375
         order by t.TrackId
         limit 10`

I have get logic plan

<img width="489" alt="image" src="https://github.com/datafusion-contrib/datafusion-federation/assets/1720962/d9a4d677-6b3e-473f-9963-44a81ccee053">

where t.trackid > Int64  does not pushdown?

How to do this optimization?

**Comment by backkem** [comment]
You are right. To improve on these cases, the plan will have to be re-written prior to cutting it into sub-plans for federation. I've yet to look into this.

To avoid full table reads on both sides of the join we'd need apache/arrow-datafusion#7955.
