### ISSUE TITLE
Provide FlightSQLExecutor::new() and FlightSQLExecutor::new_with_client() methods

### ISSUE THREAD

**Issue by devinjdangelo** [datafusion-contrib/datafusion-federation#6]
Currently we only have FlightSQLExecutor::new() which requires passing a fully configured / authenticated FlightSQLServiceClient. We could break this into two methods, one which allows full control (FlightSQLExecutor::new_with_client()) and one that provides sensible default options / basic configuration for the 90% use cases (FlightSQLExecutor::new()), e.g. basic auth or unauthenticated.

**Comment by backkem** [comment]
Closing in favor of #62.
