### ISSUE TITLE
Proposal: Automate Deployment and Changelog Generation

### ISSUE THREAD

**Issue by hozan23** [datafusion-contrib/datafusion-federation#72]
Hello

I'd like to propose a couple of improvements to the repository:

- Automated Deployment to `crates.io`:

  Currently, the deployment of `datafusion-federation` and `datafusion-flight-sql-server` crates to crates.io is done manually. We could use github actions to automate the deployment process for all the crates in this repository. 

- Automated Changelog Generation:

  It would be helpful to generate a changelog for new releases of `datafusion-federation` crate automatically.

I came across the tool [release-plz](https://release-plz.ieni.dev/) that could help with both automating the deployment to crates.io and generating changelogs. It also supports version bumping based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

Please let me know your thoughts on this.

@backkem @phillipleblanc @nathanielc 
Thank you

**Comment by phillipleblanc** [comment]
+1 from me.

One way to do this is to leverage GitHub releases. There is a way to automatically generate release notes via GitHub releases (https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) and you can trigger workflows based on a release being created that will go and deploy to `crates.io`. 

Here is an example of the auto-generated release notes: https://github.com/datafusion-contrib/datafusion-table-providers/releases/tag/v0.2.3

**Comment by nathanielc** [comment]
+1 from me as well. I use conventional commits out of habit these days anyway. I am not too picky on how it gets done, I have had success with cargo based tooling for generating both the release notes and publishing to crates.io. If its helpful [here](https://github.com/ceramicnetwork/rust-ceramic/tree/main/.github/workflows) are some workflows that do this for another rust project I work on. 

The process of creating a release is to run the create a release workflow manually when we want to create a release. It then creates a PR we can review the release notes etc. When the PR merges the second workflow picks it up and publishes the release to github/crates.io. 

We don't need that involved of a process but thought I'd share in case its useful.

**Comment by hozan23** [comment]
Thank you @phillipleblanc and @nathanielc for your suggestions. 
I will create a PR soon and submit it for your review.
